### ISSUE TITLE
FW: Configuração junit-context.xml

### ISSUE THREAD

**Issue by dsidcpespap** [dsidcpespap/SRVI#2]
([Id](https://mail.google.com/mail/u/0/#all/15eb90653613f834 "Open by id") | [Time](https://mail.google.com/mail/#advanced-search/subset=all&has=FW%3A%20Configura%C3%A7%C3%A3o%20junit-context.xml&within=1d&date=25%20de%20setembro%20de%202017%20%C3%A0s%2013%3A32 "Search by subject + time")) [Irma Santos](Irma.Santos@espap.pt) 25 de setembro de 2017 às 13:32:

**From:** Irma Santos **Sent:** segunda-feira, 25 de setembro de 2017 13:28
To: <ricardo.carvalho.ribeiro.sa@everis.com> Cc: Nuno Freitas <Nuno.Freitas@espap.pt> ; Cristina Gomes <Cristina.Gomes@espap.pt> **Subject:** Configuração junit-context.xml

Boas,

Este mail é mais direcionado para o Ricardo porque está a precisar no imediato este tipo de teste. Para as restantes pessoas do email é terem conhecimento deste tema.

Alterei o ficheiro junit-context.xml de forma a não dar erro de dependências e acrescentei uma classe de teste como guideline da utilização Junit com Spring, JUnitServiceExampleTest.java.

Para executar, basta selecionar a classe teste e fazer Run As JUnit Test.

Obrigada

Cumprimentos, Irma Santos

**Comment by irsaespap2016** [comment]
Done
