### ISSUE TITLE
Correcção do texto de Instruções do Granel (Ricardo Ribeiro)

### ISSUE THREAD

**Issue by dsidcpespap** [dsidcpespap/SRVI#3]
Cristina Ganchinho - eSPap
no ponto dois PE's
Sent on:
2:47 pm
From:
Cristina Ganchinho - eSPap
depois temos coluna matricula
From:
Cristina Ganchinho - eSPap
substituir matricula por ponto de entrega please

From:
Ricardo Ribeiro - eSPap (Everis)
ok

**Comment by irsaespap2016** [comment]
Enquanto não adicionar mais utilizadores ao projecto identifico na identificação do issue o nome do utilizador que foi assignado o issue. Na práctica assigno o issue a mim para puder fechar.
