### ISSUE TITLE
Geração dos templates a pedido através de JUnit Test e refactoring da implementação (Ricardo Ribeiro)

### ISSUE THREAD

**Issue by dsidcpespap** [dsidcpespap/SRVI#4]
- [X ] Geração dos templates a pedido através de Junit teste;

- [ X] Refactoring da implementação: o download acede ao ficheiro e popula com os dados do contrato associado;

**Comment by irsaespap2016** [comment]
Enquanto não adicionar mais utilizadores ao projecto identifico na identificação do issue o nome do utilizador que foi assignado o issue. Na práctica assigno o issue a mim para puder fechar.
