### ISSUE TITLE
Alteração das configurações do log4j (Ricardo Ribeiro)

### ISSUE THREAD

**Issue by dsidcpespap** [dsidcpespap/SRVI#6]
- [ ] Verificar o ficheiro de configuração: indexes, tamanho do ficheiro;

- [ ] Mudar a extensão de identificador para dia/mes/ano;

- [ ] Testes em DEV e QA;

- [ ] Alterar o nível de log dos jobs, não aparecem na nova configuração;

**Comment by irsaespap2016** [comment]
Enquanto não adicionar mais utilizadores ao projecto identifico na identificação do issue o nome do utilizador que foi assignado o issue. Na práctica assigno o issue a mim para puder fechar.
